angular.module('MyApp')
	.controller('giglCtrl', ['$scope', function($scope) {

        $scope.tianDian = true;
        $scope.toggleTianDian = function() {
            $scope.tianDian = $scope.tianDian === false ? true: false;
        };
        $scope.yinLiao = true;
        $scope.toggleYinLiao = function() {
            $scope.yinLiao = $scope.yinLiao === false ? true: false;
        };
        $scope.zhuShi = true;
        $scope.toggleZhuShi = function() {
            $scope.zhuShi = $scope.zhuShi === false ? true: false;
        };
        $scope.naiZhi = true;
        $scope.toggleNaiZhi = function() {
            $scope.naiZhi = $scope.naiZhi === false ? true: false;
        };
        $scope.shuiGuo = true;
        $scope.toggleShuiGuo = function() {
            $scope.shuiGuo = $scope.shuiGuo === false ? true: false;
        };
        $scope.douLei = true;
        $scope.toggleDouLei = function() {
            $scope.douLei = $scope.douLei === false ? true: false;
        };
        $scope.shuShi = true;
        $scope.toggleShuShi = function() {
            $scope.shuShi = $scope.shuShi === false ? true: false;
        };
        $scope.jianGuo = true;
        $scope.toggleJianGuo = function() {
            $scope.jianGuo = $scope.jianGuo === false ? true: false;
        };
        $scope.lingShi = true;
        $scope.toggleLingShi = function() {
            $scope.lingShi = $scope.lingShi === false ? true: false;
        };
        $scope.shuCai = true;
        $scope.toggleShuCai = function() {
            $scope.shuCai = $scope.shuCai === false ? true: false;
        };

        $scope.foodOrder = "type";
        $scope.reverse = true;
        $scope.sortBy = function(orderColumn) {
        	$scope.reverse = ($scope.foodOrder === orderColumn) ? !$scope.reverse : false;
    		$scope.foodOrder = orderColumn;
        }


        $scope.giglFood = [
        	{
				"name":"巧克力蛋糕",
				"gip":38,
				"gim":54,
				"fw":111,
				"cbw":52,
				"gl":20,
				"type":"甜点类"},
			{
				"name":"霜糖杯子蛋糕",
				"gip":72,
				"gim":104,
				"fw":38,
				"cbw":26,
				"gl":19,
				"type":"甜点类"},
			{
				"name":"胡萝卜蛋糕（椰子面粉）",
				"gip":36,
				"gim":52,
				"fw":60,
				"cbw":23,
				"gl":8,
				"type":"甜点类"},
			{
				"name":"黄油磅蛋糕",
				"gip":38,
				"gim":54,
				"fw":60,
				"cbw":25,
				"gl":9,
				"type":"甜点类"},
			{
				"name":"甜甜圈",
				"gip":75,
				"gim":107,
				"fw":50,
				"cbw":20,
				"gl":15,
				"type":"甜点类"},
			{
				"name":"蓝莓马芬",
				"gip":50,
				"gim":72,
				"fw":60,
				"cbw":31,
				"gl":15,
				"type":"甜点类"},
			{
				"name":"热香饼（小麦粉）",
				"gip":80,
				"gim":114,
				"fw":80,
				"cbw":20,
				"gl":16,
				"type":"甜点类"},
			{
				"name":"泡芙",
				"gip":56,
				"gim":80,
				"fw":50,
				"cbw":20,
				"gl":11,
				"type":"甜点类"},
			{
				"name":"司康饼",
				"gip":92,
				"gim":131,
				"fw":25,
				"cbw":9,
				"gl":8,
				"type":"甜点类"},
			{
				"name":"燕麦饼干",
				"gip":55,
				"gim":79,
				"fw":25,
				"cbw":16,
				"gl":9,
				"type":"甜点类"},
			{
				"name":"黑巧克力",
				"gip":23,
				"gim":33,
				"fw":50,
				"cbw":26,
				"gl":6,
				"type":"甜点类"},
			{
				"name":"牛奶巧克力",
				"gip":43,
				"gim":61,
				"fw":50,
				"cbw":28,
				"gl":12,
				"type":"甜点类"},
			{
				"name":"Tooheys啤酒",
			 	"gip":66,
			 	"gim":94,
			 	"fw":"250ml",
			 	"cbw":8,
			 	"gl":5,
			 	"type":"饮料类"},
			{
				"name":"可口可乐",
				"gip":63,
				"gim":90,
				"fw":"250ml",
				"cbw":26,
				"gl":16,
				"type":"饮料类"},
			{
				"name":"香蕉奶昔",
				"gip":30,
				"gim":43,
				"fw":"250ml",
				"cbw":26,
				"gl":8,
				"type":"饮料类"},
			{
				"name":"养乐多",
				"gip":46,
				"gim":66,
				"fw":"65ml",
				"cbw":12,
				"gl":6,
				"type":"饮料类"},
			{
				"name":"雀巢速溶热巧克力",
				"gip":51,
				"gim":73,
				"fw":"250ml",
				"cbw":23,
				"gl":12,
				"type":"饮料类"},
			{
				"name":"百吉饼",
				"gip":69,
				"gim":99,
				"fw":70,
				"cbw":35,
				"gl":24,
				"type":"主食类"},
			{
				"name":"全麦面包",
				"gip":52,
				"gim":74,
				"fw":30,
				"cbw":20,
				"gl":10,
				"type":"主食类"},
			{
				"name":"杂粮面包",
				"gip":54,
				"gim":77,
				"fw":30,
				"cbw":15,
				"gl":8,
				"type":"主食类"},
			{
				"name":"白面包",
				"gip":88,
				"gim":126,
				"fw":30,
				"cbw":14,
				"gl":12,
				"type":"主食类"},
			{
				"name":"早餐大麦片",
				"gip":69,
				"gim":99,
				"fw":30,
				"cbw":20,
				"gl":14,
				"type":"主食类"},
			{
				"name":"早餐玉米片",
				"gip":74,
				"gim":106,
				"fw":30,
				"cbw":25,
				"gl":19,
				"type":"主食类"},
			{
				"name":"燕麦粥",
				"gip":55,
				"gim":79,
				"fw":250,
				"cbw":23,
				"gl":13,
				"type":"主食类"},
			{
				"name":"袋装速溶麦片",
				"gip":83,
				"gim":119,
				"fw":250,
				"cbw":22,
				"gl":18,
				"type":"主食类"},
			{
				"name":"玉米粒",
				"gip":52,
				"gim":74,
				"fw":150,
				"cbw":28,
				"gl":15,
				"type":"主食类"},
			{
				"name":"甜玉米",
				"gip":55,
				"gim":79,
				"fw":150,
				"cbw":32,
				"gl":18,
				"type":"主食类"},
			{
				"name":"小米粥",
				"gip":62,
				"gim":88,
				"fw":150,
				"cbw":36,
				"gl":22,
				"type":"主食类"},
			{
				"name":"白米饭",
				"gip":83,
				"gim":119,
				"fw":150,
				"cbw":36,
				"gl":30,
				"type":"主食类"},
			{
				"name":"糙米饭",
				"gip":87,
				"gim":124,
				"fw":150,
				"cbw":33,
				"gl":29,
				"type":"主食类"},
			{
				"name":"白米粥",
				"gip":69,
				"gim":99,
				"fw":150,
				"cbw":33,
				"gl":23,
				"type":"主食类"},
			{
				"name":"荞麦面条",
				"gip":59,
				"gim":85,
				"fw":180,
				"cbw":42,
				"gl":25,
				"type":"主食类"},
			{
				"name":"龙口粉丝（绿豆粉丝）",
				"gip":39,
				"gim":56,
				"fw":180,
				"cbw":45,
				"gl":18,
				"type":"主食类"},
			{
				"name":"米粉",
				"gip":61,
				"gim":87,
				"fw":180,
				"cbw":39,
				"gl":23,
				"type":"主食类"},
			{
				"name":"面条",
				"gip":82,
				"gim":117,
				"fw":180,
				"cbw":42,
				"gl":34,
				"type":"主食类"},
			{
				"name":"乌冬面",
				"gip":62,
				"gim":89,
				"fw":180,
				"cbw":48,
				"gl":30,
				"type":"主食类"},
			{
				"name":"香草巧克力冰淇淋",
				"gip":57,
				"gim":82,
				"fw":50,
				"cbw":10,
				"gl":6,
				"type":"奶制品类"},
			{
				"name":"低脂牛奶",
				"gip":30,
				"gim":43,
				"fw":"250ml",
				"cbw":13,
				"gl":4,
				"type":"奶制品类"},
			{
				"name":"酸奶",
				"gip":19,
				"gim":28,
				"fw":200,
				"cbw":14,
				"gl":3,
				"type":"奶制品类"},
			{
				"name":"苹果",
				"gip":39,
				"gim":56,
				"fw":120,
				"cbw":16,
				"gl":6,
				"type":"水果类"},
			{
				"name":"香蕉",
				"gip":47,
				"gim":67,
				"fw":120,
				"cbw":24,
				"gl":11,
				"type":"水果类"},
			{
				"name":"木瓜",
				"gip":56,
				"gim":80,
				"fw":120,
				"cbw":8,
				"gl":5,
				"type":"水果类"},
			{
				"name":"菠萝",
				"gip":66,
				"gim":94,
				"fw":120,
				"cbw":19,
				"gl":8,
				"type":"水果类"},
			{
				"name":"西瓜",
				"gip":72,
				"gim":103,
				"fw":120,
				"cbw":6,
				"gl":4,
				"type":"水果类"},
			{
				"name":"橙子",
				"gip":40,
				"gim":57,
				"fw":120,
				"cbw":11,
				"gl":4,
				"type":"水果类"},
			{
				"name":"橙汁",
				"gip":46,
				"gim":66,
				"fw":"250ml",
				"cbw":26,
				"gl":12,
				"type":"水果类"},
			{
				"name":"鹰嘴豆",
				"gip":36,
				"gim":51,
				"fw":150,
				"cbw":30,
				"gl":11,
				"type":"豆类"},
			{
				"name":"芸豆",
				"gip":22,
				"gim":31,
				"fw":150,
				"cbw":25,
				"gl":6,
				"type":"豆类"},
			{
				"name":"绿豆",
				"gip":31,
				"gim":44,
				"fw":150,
				"cbw":17,
				"gl":5,
				"type":"豆类"},
			{
				"name":"大豆",
				"gip":15,
				"gim":21,
				"fw":150,
				"cbw":6,
				"gl":1,
				"type":"豆类"},
			{
				"name":"汉堡包（麦当劳）",
				"gip":66,
				"gim":94,
				"fw":95,
				"cbw":25,
				"gl":17,
				"type":"熟食类"},
			{
				"name":"麦香鱼汉堡（麦当劳）",
				"gip":66,
				"gim":94,
				"fw":128,
				"cbw":30,
				"gl":20,
				"type":"熟食类"},
			{
				"name":"麦香鸡汉堡（麦当劳）",
				"gip":66,
				"gim":94,
				"fw":186,
				"cbw":40,
				"gl":26,
				"type":"熟食类"},
			{
				"name":"芝士意大利面",
				"gip":37,
				"gim":53,
				"fw":200,
				"cbw":22,
				"gl":8,
				"type":"熟食类"},
			{
				"name":"小笼包",
				"gip":39,
				"gim":56,
				"fw":100,
				"cbw":30,
				"gl":12,
				"type":"熟食类"},
			{
				"name":"肉葱饺子",
				"gip":28,
				"gim":40,
				"fw":100,
				"cbw":21,
				"gl":6,
				"type":"熟食类"},
			{
				"name":"三文鱼寿司",
				"gip":48,
				"gim":69,
				"fw":100,
				"cbw":36,
				"gl":17,
				"type":"熟食类"},
			{
				"name":"腰果",
				"gip":25,
				"gim":36,
				"fw":50,
				"cbw":12,
				"gl":3,
				"type":"坚果类"},
			{
				"name":"花生",
				"gip":7,
				"gim":10,
				"fw":50,
				"cbw":4,
				"gl":0,
				"type":"坚果类"},
			{
				"name":"爆米花",
				"gip":65,
				"gim":94,
				"fw":20,
				"cbw":11,
				"gl":7,
				"type":"其他零食类"},
			{
				"name":"薯片",
				"gip":56,
				"gim":80,
				"fw":50,
				"cbw":21,
				"gl":12,
				"type":"其他零食类"},
			{
				"name":"蔗糖",
				"gip":65,
				"gim":94,
				"fw":10,
				"cbw":10,
				"gl":7,
				"type":"糖类"},
			{
				"name":"麦芽糖",
				"gip":105,
				"gim":150,
				"fw":10,
				"cbw":10,
				"gl":11,
				"type":"糖类"},
			{
				"name":"乳糖",
				"gip":46,
				"gim":66,
				"fw":10,
				"cbw":10,
				"gl":5,
				"type":"糖类"},
			{
				"name":"葡萄糖",
				"gip":103,
				"gim":147,
				"fw":10,
				"cbw":10,
				"gl":10,
				"type":"糖类"},
			{
				"name":"蜂蜜",
				"gip":74,
				"gim":105,
				"fw":25,
				"cbw":21,
				"gl":16,
				"type":"糖类"},
			{
				"name":"果糖",
				"gip":15,
				"gim":22,
				"fw":10,
				"cbw":10,
				"gl":2,
				"type":"糖类"},
			{
				"name":"青豌豆",
				"gip":54,
				"gim":77,
				"fw":80,
				"cbw":7,
				"gl":4,
				"type":"蔬菜类"},
			{
				"name":"南瓜",
				"gip":64,
				"gim":91,
				"fw":80,
				"cbw":9,
				"gl":6,
				"type":"蔬菜类"},
			{
				"name":"胡萝卜",
				"gip":39,
				"gim":56,
				"fw":80,
				"cbw":6,
				"gl":2,
				"type":"蔬菜类"},
			{
				"name":"煮马铃薯",
				"gip":66,
				"gim":95,
				"fw":150,
				"cbw":19,
				"gl":13,
				"type":"蔬菜类"},
			{
				"name":"薯条",
				"gip":64,
				"gim":90,
				"fw":150,
				"cbw":32,
				"gl":21,
				"type":"蔬菜类"},
			{
				"name":"土豆泥",
				"gip":76,
				"gim":108,
				"fw":150,
				"cbw":20,
				"gl":15,
				"type":"蔬菜类"},
			{
				"name":"红薯",
				"gip":70,
				"gim":100,
				"fw":150,
				"cbw":32,
				"gl":22,
				"type":"蔬菜类"},
			{
				"name":"芋头",
				"gip":48,
				"gim":68,
				"fw":150,
				"cbw":8,
				"gl":4,
				"type":"蔬菜类"},
			{
				"name":"山药",
				"gip":54,
				"gim":77,
				"fw":150,
				"cbw":37,
				"gl":20,
				"type":"蔬菜类"}
        ]
	}]);